- name: deploy wordpress using a role
  hosts: worker01, worker02
  become: true
  vars:
    wp_version: 5.0.3
    wp_mysql_db: 'database_name'
    wp_mysql_user: 'username_here'
    wp_mysql_password: 'password_here'
    wp_webserver: nginx
    wp_sitename: example.com
    wp_admin_email: 'your@email.com'
    wp_install_dir: "/var/www/{{ wp_sitename }}"
  roles:
    - docker_role
    - wordpress_role

